[package]
name = "squeeze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.7"
bit-vec = "0.6.3"
itertools = "0.10.3"
